=== textcortex/JSON-DOC/schema/block/types/rich_text/equation/equation_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "RichTextEquation",
  "customBasePath": "jsondoc.models.block.types.rich_text.base.RichTextBase",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "const": "equation"
    },
    "equation": {
      "type": "object",
      "properties": {
        "expression": {
          "type": "string"
        }
      },
      "required": ["expression"],
      "additionalProperties": false
    },
    "annotations": {
      "type": "object",
      "properties": {
        "bold": {
          "type": "boolean"
        },
        "italic": {
          "type": "boolean"
        },
        "strikethrough": {
          "type": "boolean"
        },
        "underline": {
          "type": "boolean"
        },
        "code": {
          "type": "boolean"
        },
        "color": {
          "type": "string"
        }
      },
      "required": [
        "bold",
        "italic",
        "strikethrough",
        "underline",
        "code",
        "color"
      ]
    },
    "plain_text": {
      "type": "string"
    },
    "href": {
      "type": ["string", "null"]
    }
  },
  "required": ["type", "equation", "annotations", "plain_text", "href"],
  "unevaluatedProperties": false
}

=== textcortex/JSON-DOC/schema/block/types/rich_text/equation/ex1_success.json
{
  "type": "equation",
  "equation": {
    "expression": "\\int_0^1\\sin(x)\\,dx"
  },
  "annotations": {
    "bold": false,
    "italic": false,
    "strikethrough": false,
    "underline": false,
    "code": false,
    "color": "default"
  },
  "plain_text": "\\int_0^1\\sin(x)\\,dx",
  "href": null
}
