=== textcortex/JSON-DOC/schema/block/types/rich_text/text/text_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "RichTextText",
  "customBasePath": "jsondoc.models.block.types.rich_text.base.RichTextBase",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "const": "text",
      "default": "text"
    },
    "text": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "link": {
          "type": ["object", "null"],
          "properties": {
            "url": {
              "type": "string"
            }
          },
          "required": ["url"]
        }
      },
      "required": ["content", "link"]
    },
    "annotations": {
      "$ref": "/shared_definitions/shared_definitions_schema.json#/$defs/annotations"
    },
    "plain_text": {
      "type": "string"
    },
    "href": {
      "type": ["string", "null"]
    }
  },
  "required": ["type", "text", "annotations", "plain_text", "href"],
  "unevaluatedProperties": false
}

=== textcortex/JSON-DOC/schema/block/types/rich_text/text/ex3_success.json
{
  "type": "text",
  "text": {
    "content": "Some words ",
    "link": {
      "url": "https://example.com"
    }
  },
  "annotations": {
    "bold": false,
    "italic": false,
    "strikethrough": false,
    "underline": false,
    "code": false,
    "color": "default"
  },
  "plain_text": "Some words ",
  "href": null
}
